### PR TITLE
CLDC-639: Active admin

### PR DESCRIPTION
**Pull request by baarkerlounger**
Adds a basic admin interface with a dashboard with basic charting ability, and a case log view that allows CSV downloads

image

image

### CODE REVIEW

**Comment by dushan-madetech** [comment]
Is there any non-test data on the Gov PAAS deployment that this would give access to?

**Comment by baarkerlounger** [comment]
@dushan-madetech nope there are no real users yet. Will also put this behind auth as soon as your work goes in, just didn't want to duplicate it and get huge merge conflicts.

**Comment by dushan-madetech** [comment]
Awesome, I just wanted to check if maybe it should be locked behind something temporary like a feature flag if there was something to hide away, will go on and approve now

**Review by dushan-madetech — APPROVED** [review]
This seems good to me since there's no live data in the deployment, 🚢 it

**Pull request merged**
