### PR TITLE
CLDC-1176: date hint text

### PR DESCRIPTION
**Pull request by kiddhustle**
https://digital.dclg.gov.uk/jira/browse/CLDC-1176

### CODE REVIEW

**Comment by baarkerlounger** [comment]
Rebase on main to get audit passing

**Review by baarkerlounger — APPROVED** [review]

**Comment by paulrobertlloyd** [comment]
@Dan13L3 Full stops after hint text, correct?

**Comment by kiddhustle** [comment]
@paulrobertlloyd for the hint text I used the GOVUK design system as reference:

https://design-system.service.gov.uk/patterns/dates/#asking-for-memorable-dates

**Comment by paulrobertlloyd** [comment]
The examples in the Design System are painfully inconsistent when it comes to formatting hint text. I think we settled on using full stops…

**Comment by baarkerlounger** [comment]
I think for error messages we've said no full stop at the end unless the message itself already has one (i.e. is more than 1 sentence). Should maybe be consistent with that?

**Comment by kiddhustle** [comment]
amended to end with full stop

**Comment by paulrobertlloyd** [comment]
:shipit:

**Comment by baarkerlounger** [comment]
Let's wait for @Dan13L3 ?

**Comment by Dan13L3** [comment]
@baarkerlounger @paulrobertlloyd @kiddhustle Error messages should be without a full stop (unless more than 1 sentence), and hint text with (I think it helps differentiate it from sub headers, etc). But Paul's right: even GDS can't make its mind up :)

**Review by baarkerlounger — APPROVED** [review]

**Pull request merged**
