### PR TITLE
Format account locked view

### PR DESCRIPTION
**Pull request by baarkerlounger**
image

### CODE REVIEW

**Review by dushan-madetech — APPROVED** [review]
Code wise it looks fine 👍

**Comment by Dan13L3** [comment]
Hi @baarkerlounger Can we go with this:

Too many incorrect login attempts [h1]

Your account has been locked for security reasons.

Contact another helpdesk administrator for access.

**Comment by baarkerlounger** [comment]
@Dan13L3 Is that "Header", "Paragraph", "Paragraph"?

**Comment by Dan13L3** [comment]
@baarkerlounger yes please

**Comment by baarkerlounger** [comment]
@Dan13L3 updated.

**Comment by Dan13L3** [comment]
@baarkerlounger looks good - thanks!

**Comment by Dan13L3** [comment]
@baarkerlounger arrgh, sorry - should have 'for access' on the end of that last sentence too. Would you mind adding?

**Comment by baarkerlounger** [comment]
@Dan13L3 updated text and screenshot.

**Pull request merged**
