### PR TITLE
Add error to postcode for LA validation

### PR DESCRIPTION
**Pull request by baarkerlounger**
image

### CODE REVIEW

**Comment by baarkerlounger** [comment]
@Dan13L3 could you check this error message?

**Comment by Dan13L3** [comment]
@baarkerlounger This would be better as: 'Postcode must be in an area covered by this service'

**Comment by baarkerlounger** [comment]
@Dan13L3 `Postcode must be in an area covered by %{organisation_name}`? It is specific to the org, not the service as a whole.

**Comment by Dan13L3** [comment]
@baarkerlounger Ahh, okay. Your suggestion works then!

**Pull request merged**
