### PR TITLE
rename indexes

### PR DESCRIPTION
**Pull request by kosiakkatrina**
Generated this by deleting the schema file, recreating tables and applying the migrations

### CODE REVIEW

**Comment by baarkerlounger** [comment]
Could be wrong but without a migration I don't _think_ this will actually change the index names of prod database, so would lead to the schema potentially not matching what's actually there.

Might be better as @jamesrose suggested to write a migration that removes the old index and adds this one to achieve this result.

**Comment by dushan-madetech** [comment]
> Could be wrong but without a migration I don't _think_ this will actually change the index names of prod database, so would lead to the schema potentially not matching what's actually there.
> 
> Might be better as @jamesrose suggested to write a migration that removes the old index and adds this one to achieve this result.

@baarkerlounger This is actually done by [this migration](https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data/blob/main/db/migrate/20220823083657_change_case_log_to_lettings_log.rb) but in the process of rebasing the large rename branch multiple times the case logs bit slipped through. You could see this by dropping the databases, creating them and then running the migrations (on main) and you'll end up with the same diff as this PR

**Comment by baarkerlounger** [comment]
@dushan-madetech that migration renames the table but unless I'm missing something it doesn't rename the indexes on it?

**Comment by kosiakkatrina** [comment]
> @dushan-madetech that migration renames the table but unless I'm missing something it doesn't rename the indexes on it?

@baarkerlounger it did for me, try rolling back and migrating

**Review by baarkerlounger — APPROVED** [review]

**Pull request merged**
